spring:
  application:
    name: mobile-service
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test;
    data-username: sa
    data-password:
  jpa:
    show-sql: true
  transaction:
    default-timeout: 60
server:
  port: 8080
  ssl:
    enabled: false
